on:
    push:
        paths:
            - "translations/**"
    workflow_dispatch:

jobs:
    create-diff-file:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Update differences/
              run: npm run diff

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  # Optional. Commit message for the created commit.
                  # Defaults to "Apply automatic changes"
                  commit_message: Update differences/

                  # Optional glob pattern of files which should be added to the commit
                  # Defaults to all (.)
                  # See the `pathspec`-documentation for git
                  # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
                  # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
                  file_pattern: "differences/*"
